### ISSUE TITLE
LG OLED C9 (webOS 4.9) GDB problem

### ISSUE THREAD

**Issue by teclamat** [pzlds/webos-key-reader#2]
Since you welcome feedback from other devices, I have one from 2019 model (C9).

**Device info:**
* Model: OLED65C9PLA
* Firmware: 05.30.40
* webOS: 4.9.0
* OTA ID: HE_DTV_W19O_AFABABAA
* Rooted: yes

I can find mentioned function inside `tvservice` just fine:

```
(gdb) info fun DvrKey                               
All functions matching regular expression "DvrKey":

File os/common_linux/dil/pvr/dil_pvr_debug.c:
enum {API_OK, OK = 0, API_ERROR = -1, API_NOT_OK = -1, NOT_OK = -1, PARAMETER_ERROR = -2, API_INVALID_PARAMS = -2, INVALID_PARAMS = -2, 
    API_NOT_ENOUGH_RESOURCE = -3, NOT_ENOUGH_RESOURCE = -3, API_NOT_SUPPORTED = -4, NOT_SUPPORTED = -4, API_NOT_PERMITTED = -5, NOT_PERMITTED = -5, 
    API_TIMEOUT = -6, TIMEOUT = -6, NO_DATA_RECEIVED = -7, DN_BUF_OVERFLOW = -8, DLNA_NOT_CONNECTED = -9, UP_BUF_OVERFLOW = -10} PVR_DEBUG_RetrieveDvrKey(__UINT8*, 
    unsigned int *);
enum {API_OK, OK = 0, API_ERROR = -1, API_NOT_OK = -1, NOT_OK = -1, PARAMETER_ERROR = -2, API_INVALID_PARAMS = -2, INVALID_PARAMS = -2, 
    API_NOT_ENOUGH_RESOURCE = -3, NOT_ENOUGH_RESOURCE = -3, API_NOT_SUPPORTED = -4, NOT_SUPPORTED = -4, API_NOT_PERMITTED = -5, NOT_PERMITTED = -5, 
    API_TIMEOUT = -6, TIMEOUT = -6, NO_DATA_RECEIVED = -7, DN_BUF_OVERFLOW = -8, DLNA_NOT_CONNECTED = -9, UP_BUF_OVERFLOW = -10} PVR_DEBUG_SaveDvrKey(__UINT8*, 
    unsigned int);
(gdb) 
```

But I have problem with `malloc`-ing memory segments to act as function parameters:

```
(gdb) set $target_buf = (unsigned char *) malloc(16)       

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/arm/armv6t2/strlen.S:146
146     ../sysdeps/arm/armv6t2/strlen.S: No such file or directory.
The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(malloc) will be abandoned.
When the function is done executing, GDB will silently stop.
(gdb) info fun strlen
All functions matching regular expression "strlen":

Non-debugging symbols:
0xf6ebc678  u_strlen_57
0xf5415b98  g_utf8_strlen
0xf3be2974  strlen_safe
```

Do you happen to have any ideas how to allocate memory another way (which address will still be accessible by tvservice process)?

**Comment by pzlds** [comment]
I don't have any ideas from the top of my head, I guess if you don't care about the process surviving for any significantly long time you can just pick any random address from the existing address space that appears to be rarely used. The highest chance for this succeeding would require investigating whether `tvservice` or any of the other loaded libraries have unused space in their mapped `.data` sections.

It would be interesting to know what address `malloc` is returning, maybe you could run `set $target_buf = (unsigned long) malloc(16)` once you have the chance.

**Comment by teclamat** [comment]
Thanks for stopping by and giving me some ideas. So let me summarize what I found out:
1) I found in .data enough unused memory range, but still got segfault on `strlen` - probably caused by memcpy inside.
2) malloc cannot return anything because it segfaults at internal strlen call.
3) Used Ghidra on `tvservice` and found out where that key is kept in memory and finally managed to read that key without any memory allocation by printing that member:

```
(gdb) x/16b pPvrGlobalDebugInfo->dvrKey
```

Hope it might be hepful for someone.

BTW, web resource of static gdb used in your script is no more (user did hide all his repos), had problem finding working gdb on that TV. Ultimately found this one `https://github.com/lslx/arm-gdb-static/raw/master/gdb76` to be working fine.

One final remark. The key read that way doesn't have any processing done by `PVR_DEBUG_RetrieveDvrKey` (but it can be pretty easily reproduced from reverse engineered function, if needed). For example I had to xor each dvrKey byte with `0xAA` for it to work as expected on DVR recordings.

```c
undefined4 PVR_DEBUG_RetrieveDvrKey(undefined (*param_1) [16],uint *param_2)

{
  undefined auVar1 [16];
  uint uVar2;
  undefined (*pauVar3) [16];
  uint uVar4;
  byte *pbVar5;
  byte *pbVar6;
  uint uVar7;
  uint __n;
  
  if ((pPvrGlobalDebugInfo == (PVR_GLOBAL_DEBUG_INFO_T *)0x0) ||
     (uVar7 = pPvrGlobalDebugInfo->dvrKeyBitLen, *param_2 < uVar7)) {
    return 0xffffffff;
  }
  *param_2 = uVar7;
  __n = uVar7 >> 3;
  if ((uVar7 & 7) == 0) {
    memcpy(param_1,pPvrGlobalDebugInfo->dvrKey,__n);
    if (__n == 0) {
      return 0;
    }
  }
  else {
    __n = __n + 1;
    memcpy(param_1,pPvrGlobalDebugInfo->dvrKey,__n);
  }
  uVar7 = (__n - 0x10 >> 4) + 1;
  uVar4 = uVar7 * 0x10;
  if (__n - 1 < 0xf) {
    uVar4 = 0;
  }
  else {
    auVar1 = SIMDExpandImmediate(0,0xe,0xaa);
    uVar2 = 0;
    pauVar3 = param_1;
    do {
      uVar2 = uVar2 + 1;
      *(longlong *)*pauVar3 = SUB168(*pauVar3 ^ auVar1,0);
      *(longlong *)(*pauVar3 + 8) = SUB168(*pauVar3 ^ auVar1,8);
      pauVar3 = pauVar3 + 1;
    } while (uVar2 < uVar7);
    if (uVar4 == __n) {
      return 0;
    }
  }
  pbVar5 = *param_1 + uVar4;
  do {
    pbVar6 = pbVar5 + 1;
    *pbVar5 = *pbVar5 ^ 0xaa;
    pbVar5 = pbVar6;
  } while ((uint)((int)pbVar6 - (int)param_1) < __n);
  return 0;
}
```
